export const quotes = [
  "Start before you feel ready.",
  "Small steps still move you forward.",
  "Consistency beats intensity.",
  "Done is better than perfect.",
  "Discipline creates freedom.",
  "You don’t need motivation to begin.",
  "Progress, not perfection.",
  "Make it simple, then make it better.",
  "Focus on what you can control.",
  "Your future is built daily.",

  "You get better by showing up, not by waiting.",
  "Clarity comes from action.",
  "Hard days build strong habits.",
  "The work you avoid controls you.",
  "Your habits shape your identity.",
  "Start small, stay consistent.",
  "You don’t need more time, just better focus.",
  "Momentum is built, not found.",
  "Effort compounds quietly.",
  "You are one decision away from progress.",

  "Do it tired, do it anyway.",
  "What you repeat grows stronger.",
  "Action beats overthinking.",
  "You don’t rise to goals, you fall to systems.",
  "Keep going, even if it’s slow.",
  "Every step counts, even the messy ones.",
  "You’re closer than you think.",
  "The hardest part is starting again.",
  "Stop waiting for the perfect moment.",
  "Show up, even when it’s inconvenient.",

  "Build habits that future you will thank you for.",
  "The small wins matter most.",
  "Stay consistent, not extreme.",
  "Growth feels uncomfortable for a reason.",
  "You can start again today.",
  "Focus creates results.",
  "Don’t rush, just don’t stop.",
  "Your effort is never wasted.",
  "Keep your promises to yourself.",
  "One step forward is still progress.",

  "You don’t need permission to improve.",
  "Discipline is choosing what matters most.",
  "Do the work, even when it’s boring.",
  "Results come from repetition.",
  "Your future depends on today.",
  "Keep moving, no matter how small.",
  "You are building something bigger.",
  "Consistency creates confidence.",
  "You don’t fail, you learn.",
  "The process is the reward.",

  "Make progress your priority.",
  "Stay focused on your lane.",
  "You’re capable of more than you think.",
  "Every day is a fresh start.",
  "Build, adjust, repeat.",
  "Don’t quit on a bad day.",
  "You’re allowed to grow slowly.",
  "Effort beats talent over time.",
  "Start messy, finish strong.",
  "Keep showing up for yourself.",

  "Your mindset shapes your path.",
  "Stay patient, stay consistent.",
  "You are building discipline.",
  "Focus on progress, not speed.",
  "You don’t need to be perfect to begin.",
  "Do what matters, ignore the noise.",
  "Stay committed to your goals.",
  "Growth is not always visible.",
  "You’re improving every day.",
  "Trust the process.",

  "Make today count.",
  "You are in control of your effort.",
  "Discomfort means growth.",
  "Keep pushing forward.",
  "Small habits create big change.",
  "Stay consistent with the basics.",
  "Don’t let doubt stop you.",
  "You’re stronger than your excuses.",
  "Progress takes patience.",
  "Focus on what moves you forward.",

  "You don’t need to rush success.",
  "Be proud of your effort.",
  "Stay disciplined, stay focused.",
  "You’re getting better every day.",
  "Keep building momentum.",
  "Start where you are.",
  "Your actions define you.",
  "Stay consistent with your goals.",
  "You are capable of change.",
  "Keep going, no matter what.",

  "Do the work, see the results.",
  "Stay committed to growth.",
  "You’re making progress.",
  "Keep moving forward.",
  "Focus on your journey.",
  "Stay patient with yourself.",
  "Every effort counts.",
  "Keep your standards high.",
  "You’re building something meaningful.",
  "Stay consistent with your effort.",
];
